# Generated by Django 2.2.6 on 2019-10-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_auto_20191008_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_name',
            field=models.CharField(max_length=20),
        ),
    ]
