# Generated by Django 2.2.6 on 2019-10-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20191008_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dog',
            field=models.CharField(choices=[('Parker', 'Parker'), ('Jaxon', 'Jaxon'), ('Luca', 'Luca')], max_length=256),
        ),
    ]
