# Generated by Django 2.2.6 on 2019-10-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_auto_20191008_1749'),
        ('person', '0003_auto_20191008_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='dog',
        ),
        migrations.AddField(
            model_name='person',
            name='dog',
            field=models.ManyToManyField(to='dog.Dog'),
        ),
    ]
