# Generated by Django 2.2.5 on 2019-10-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
