# Generated by Django 2.2.6 on 2019-10-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20191004_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
