# Generated by Django 2.2.6 on 2019-10-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20191004_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images/'),
        ),
    ]
