# Generated by Django 2.2.6 on 2019-10-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20191008_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entry_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_title',
            new_name='title',
        ),
    ]
