# Generated by Django 2.2.6 on 2019-10-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_auto_20191008_1749'),
        ('entries', '0009_auto_20191008_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=None, to='dog.Dog'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person'),
        ),
    ]
