# Generated by Django 2.2.6 on 2019-10-08 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_auto_20191008_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dog.Dog'),
        ),
    ]
